### ISSUE TITLE
Windows Server not work

### ISSUE THREAD

**Issue by NiXyos** [timmybo5/sbox-server-manager#17]
My server not work 
![image](https://github.com/timmybo5/sbox-server-manager/assets/54945554/8d28b393-4ccd-4b9b-9b4e-7d57bd5ffae2)

**Comment by timmybo5** [comment]
Hey! Looks like you are missing the .net runtime environment, you can get the required v7 version from here: https://dotnet.microsoft.com/en-us/download/dotnet/7.0

I'll look if I can make it auto install with the next version or warn the user if not installed

**Comment by Not-Solid** [comment]
Hi, I have the same issue. Installing the runtime did not solve the issue for me. I'm also on Windows Server, any other ideas?

**Comment by timmybo5** [comment]
> Hi, I have the same issue. Installing the runtime did not solve the issue for me. I'm also on Windows Server, any other ideas?

Could you share a picture of your console output here? 👀

**Comment by Not-Solid** [comment]
> > Hi, I have the same issue. Installing the runtime did not solve the issue for me. I'm also on Windows Server, any other ideas?
> 
> Could you share a picture of your console output here? 👀

It is identical to the previously posted screenshot. I have also tried switching from windows server to win 11 but to no avail.
I am using azure vms for this. It works fine on my local pc though.

**Comment by NiXyos** [comment]
it's good for me
