### ISSUE TITLE
TTT server crash problem

### ISSUE THREAD

**Issue by NiXyos** [timmybo5/sbox-server-manager#18]
Hello I have set up a TTT server and the server only crashes when there are a lot of players yet I have an AMD Ryzen 7 3800X - 8c/16t - 3.9 GHz/4.5 GHz with 128 GB DDR4 ECC .
Do you think you can give me an idea for my server or is it possible the possibility of the automatic restart?

**Comment by timmybo5** [comment]
This sounds like a TTT issue, I'm planning to add an auto restart feature for the next release
